[header_chain]
enable = false 
init_input = false 
esplora_url = "http://127.0.0.1:13002"
start = 116000
#start = 1000
block_headers = "../circuits/data/header-chain/block_headers.bin"
force_fetch = true 

batch_size = 10 
input_proof = "../circuits/data/header-chain/0-116000.bin"
output_proof = "../circuits/data/header-chain/116000-10.bin"
bitcoin_network = "testnet4"

[commit_chain]
enable = false 
esplora_url = "http://127.0.0.1:13002"
commit_info = "../circuits/data/commit-chain/commit_info.json.0"
commits = "../circuits/data/commit-chain/commits.bin"
init_input = true 
start = 0 
batch_size = 1
input_proof = "../circuits/data/commit-chain/0-1.bin"
output_proof = "../circuits/data/commit-chain/0-1.bin"
bitcoin_network = "testnet4"

[state_chain]
enable = false 
init_input = true 
#l2_contract_address = "0x21f619040AC2eAcacEF8Fe17Ae8bDF53ec69C66f"
l2_contract_address = "0x26Aa99d72f5f85D60A1B44773B3897793981B7F7"
#proceed_withdraw_method_id = "0xc3342df3"
proceed_withdraw_method_id = "0xd3d8a3f4"
#start = 9511050
start = 10207974
batch_size = 40
execution_layer_rpc = "https://rpc.testnet3.goat.network"
blocks = "../circuits/data/state-chain/state.blocks"
## input_proof is optional when init_input=true
input_proof = "../circuits/data/state-chain/10207974-40.bin"
output_proof = "../circuits/data/state-chain/10207974-40.bin"
goat_network = "goattest"
cosmos_rpc_url = "https://rpc.testnet3.goat.network/goat-rpc"

[watchtower]
enable = false 
esplora_url = "http://127.0.0.1:13002"
genesis_sequencer_commit_txid = "eae1e2638ce347deadcef7d6c4f0dd6776317adb9ee2abdd2514aa3cdc41c9c9"
latest_sequencer_commit_txid = "3b915823880bb347b102731d3d2d4538673f8e3a1b453858d89476381029f9b0"
header_chain_input_proof = "../circuits/data/header-chain/0-116000.bin"
commit_chain_input_proof = "../circuits/data/commit-chain/2-1.bin"
state_chain_input_proof = "../circuits/data/state-chain/10207974-40.bin"
output = "../circuits/data/watchtower/output.bin"
index = 1
bitcoin_network = "testnet4"

[operator]
enable = true 
esplora_url = "http://127.0.0.1:13002"
genesis_sequencer_commit_txid = "eae1e2638ce347deadcef7d6c4f0dd6776317adb9ee2abdd2514aa3cdc41c9c9"
latest_sequencer_commit_txid = "3b915823880bb347b102731d3d2d4538673f8e3a1b453858d89476381029f9b0"
watchtower_challenge_init_txid = "ad62af8aec5c7eb4966170b1931d9348292cd7797d5dc8c436afecb5e9c38bde"
watchtower_challenge_txids = "5d6d5e49efddef613ca98d72987ee806c987df488a8479e69f2fe419b5321bf1"
watchtower_public_keys = "03e7a08db9093c279535bd0078582469b82bf9f12c6dcb7588e187d2b9cc724279" 

header_chain_input_proof = "/home/ubuntu/data/proof-builder-rpc/circuits/data/header-chain/117590-10.bin"
commit_chain_input_proof = "/home/ubuntu/data/proof-builder-rpc/circuits/data/commit-chain/6-1.bin"
state_chain_input_proof =  "/home/ubuntu/data/proof-builder-rpc/circuits/data/state-chain/10285644-40.bin"
output = "../circuits/data/operator/output.bin"
included_watchtowers = "1"
graph_id="91931F68ABC34F9EB6EED37264581B2C"
execution_layer_block_number = 10285657
index = 1
bitcoin_network = "testnet4"
