-- Add migration script here
DROP TABLE IF EXISTS `graph`;
CREATE TABLE graph
(
    `graph_id`                           TEXT            NOT NULL DEFAULT '',
    `instance_id`                        TEXT            NOT NULL,
    `kickoff_index`                      BIGINT UNSIGNED NOT NULL DEFAULT 0,
    `from_addr`                          TEXT            NOT NULL DEFAULT '',
    `to_addr`                            TEXT            NOT NULL DEFAULT '',
    `graph_ipfs_base_url`                TEXT            NOT NULL DEFAULT '',
    `amount`                             BIGINT UNSIGNED NOT NULL DEFAULT 0,
    `challenge_amount`                   BIGINT UNSIGNED NOT NULL DEFAULT 0,
    `status`                             TEXT            NOT NULL DEFAULT '',
    `sub_status`                         TEXT            NOT NULL DEFAULT '',
    `operator_pubkey`                    TEXT            NOT NULL DEFAULT '',
    `cur_prekickoff_txid`                TEXT,
    `next_prekickoff`                    TEXT,
    `force_skip_kickoff_txid`            TEXT,
    `quick_challenge_txid`               TEXT,
    `challenge_incomplete_kickoff_txid`  TEXT,
    `pegin_txid`                         TEXT,
    `kickoff_txid`                       TEXT,
    `take1_txid`                         TEXT,
    `challenge_txid`                     TEXT,
    `take2_txid`                         TEXT,
    `disprove_txid`                      TEXT,
    `watchtower_challenge_init_txid`     TEXT,
    `watchtower_challenge_timeout_txids` TEXT            NOT NULL DEFAULT '[]',
    `nack_txids`                         TEXT            NOT NULL DEFAULT '[]',
    `blockhash_commit_timeout_txid`      TEXT,
    `assert_init_txid`                   TEXT,
    `assert_commit_timeout_txids`        TEXT            NOT NULL DEFAULT '[]',
    `init_withdraw_tx_hash`              TEXT,
    `bridge_out_start_at`                BIGINT          NOT NULL DEFAULT 0,
    `zkm_version`                        TEXT            NOT NULL DEFAULT '',
    `status_updated_at`                  BIGINT          NOT NULL DEFAULT 0,
    `proceed_withdraw_height`            BIGINT          NOT NULL DEFAULT 0,
    `created_at`                         BIGINT          NOT NULL DEFAULT 0,
    `updated_at`                         BIGINT          NOT NULL DEFAULT 0,
    PRIMARY KEY (`graph_id`)
);
