[package]
name = "commit-chain-rpc"
version.workspace = true
edition.workspace = true

[dependencies]
reqwest = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
base64 = { workspace = true }

bitcoin-light-client-circuit = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }

[lints]
workspace = true