name: Time-consuming test

on:
  push:
    branches: ["main", "dev"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Cargo Test
    runs-on: [self-hosted, bitvm2-node]
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@nightly
      - name: Run all unit tests
        run:  |
          source ~/.zkm-toolchain/env 
          cd crates/bitvm-gc
          cargo test -r --features ci-tests -- --nocapture
